import { Gothic_A1 } from "next/font/google";
import "./globals.css";

const gothicAI = Gothic_A1({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],  // You can adjust weights as needed
  variable: "--font-gothic-ai",
  subsets: ["latin"],
});

export const metadata = {
  title: "Benjamin | Graphic Designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gothicAI.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}